### ISSUE TITLE
pip doesnt install dependencies 

### ISSUE THREAD

**Issue by ThatCopy** [thenamesweretakenalready/Sv443s-JokeAPI-Python-Wrapper#3]
`pip install jokeapi` doesnt install simplejson or urllib3

`pip install jokeapi`

It should install simplejson and urllib3

![image](https://user-images.githubusercontent.com/62877244/87300723-a663e500-c50e-11ea-92c3-db21cc603439.png)
The `setuptools.find_packages()` probbably fails 

 - OS: Win 10 (2004)
 - Python version 3.8
 - Version 0.2.2

**Comment by benjhar** [comment]
Fixed in #4
