### ISSUE TITLE
Example in readme doesn't work

### ISSUE THREAD

**Issue by ThatCopy** [thenamesweretakenalready/Sv443s-JokeAPI-Python-Wrapper#5]
**Describe the bug**
The example in the README.md doesn't work and throws an error 

**To Reproduce**
Run the example in README.md

**Expected behavior**
Return a joke

**Error and/or code snippet**

`
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    if joke["type"] == "single": # Print the joke
TypeError: list indices must be integers or slices, not str
`

**Please complete the following information:**
 - OS: Win 10 (2004)
 - Python version 3.8
 - Version 0.2.2
 - Installed with pip

**Comment by benjhar** [comment]
Thanks for opening this issue, it's fixed in the most recent commit.
