### ISSUE TITLE
Make a native aiohttp async mode too.

### ISSUE THREAD

**Issue by JDJGInc** [thenamesweretakenalready/Sv443s-JokeAPI-Python-Wrapper#9]
**Is your feature request related to a problem? Please describe.**
Basically there's no native async branch sure you could do an executor, but it's not as useful as native async.

**Describe the solution you'd like**
make it mutlisync a way to do it with either aiohttp or requests, I guess?
just both sync and sync.

**Describe alternatives you've considered**
I currently use aiohttp session's directly.

**Additional context**

**Comment by benjhar** [comment]
Hi, thanks for making an issue.

I like what you're suggesting here, but I want to check that I've grasped it correctly. You're suggesting I write an asynchronous version of the `get_joke` function (and, I suppose, other functions)?

**Comment by JDJGInc** [comment]
yes.
sorry for the late response.
a.k.a an aiohttp mode.
